# Generated by Django 4.1.7 on 2023-04-28 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0001_initial'),
        ('social', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='purchased_by',
            field=models.ManyToManyField(editable=False, related_name='recipes_shopped', through='shopping.CartItem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rated_by',
            field=models.ManyToManyField(editable=False, related_name='recipes_rated', through='social.RatingRecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='uploads',
            field=models.ManyToManyField(blank=True, to='recipes.mediaupload'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='uploads',
            field=models.ManyToManyField(blank=True, to='recipes.mediaupload'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientname'),
        ),
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uploads',
            field=models.ManyToManyField(blank=True, to='recipes.mediaupload'),
        ),
    ]
